services:
  postgres:
    image: postgres:16
    container_name: attrib-postgres
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-attrib}
      POSTGRES_USER: ${DB_USER:-attrib}
      POSTGRES_PASSWORD: ${DB_PASS:-attrib}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U ${DB_USER:-attrib} -d ${DB_NAME:-attrib}"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: attrib-adminer
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  minio:
    image: minio/minio:latest
    container_name: attrib-minio
    command: ["server","/data","--console-address",":9001"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-adminadmin}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  minio-setup:
    image: minio/mc:latest
    container_name: attrib-minio-setup
    depends_on:
      - minio
    command:
      - sh
      - -lc
      - >
        set -e;
        until mc alias set local http://minio:9000 ${MINIO_ROOT_USER:-admin} ${MINIO_ROOT_PASSWORD:-adminadmin}; do
          echo "waiting for minio...";
          sleep 2;
        done;
        mc mb -p local/dp-raw || true;
        mc mb -p local/dp-bronze || true;
        mc mb -p local/dp-silver || true;
        mc mb -p local/dp-gold || true;
        mc anonymous set download local/dp-raw || true;
        mc anonymous set download local/dp-bronze || true;
        mc anonymous set download local/dp-silver || true;
        mc anonymous set download local/dp-gold || true;
    restart: "no"
  metabase:
    image: metabase/metabase@sha256:953cc94ad545b4a866d355d03d33c10d3a2f089842dba7b3b1d9769597b562f5
    container_name: attrib-metabase
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_DBNAME: ${DB_NAME:-attrib}
      MB_DB_USER: ${DB_USER:-attrib}
      MB_DB_PASS: ${DB_PASS:-attrib}
      MB_ENCRYPTION_SECRET: jeocutmdlhfdomvtbecwzibpmpwncytk
      MB_SITE_URL: http://localhost:3000
      MB_JETTY_PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped


volumes:
  pgdata:
  minio-data:

networks:
  default:
    name: attrib-net